/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCreateUserRouteImport } from './routes/api/public/create-user'
import { Route as ApiPublicCreateRouteImport } from './routes/api/public/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateUserRoute = ApiPublicCreateUserRouteImport.update({
  id: '/api/public/create-user',
  path: '/api/public/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateRoute = ApiPublicCreateRouteImport.update({
  id: '/api/public/create',
  path: '/api/public/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/create': typeof ApiPublicCreateRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/create': typeof ApiPublicCreateRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/create': typeof ApiPublicCreateRoute
  '/api/public/create-user': typeof ApiPublicCreateUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/create' | '/api/public/create-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/create' | '/api/public/create-user'
  id: '__root__' | '/' | '/api/public/create' | '/api/public/create-user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCreateRoute: typeof ApiPublicCreateRoute
  ApiPublicCreateUserRoute: typeof ApiPublicCreateUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-user': {
      id: '/api/public/create-user'
      path: '/api/public/create-user'
      fullPath: '/api/public/create-user'
      preLoaderRoute: typeof ApiPublicCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create': {
      id: '/api/public/create'
      path: '/api/public/create'
      fullPath: '/api/public/create'
      preLoaderRoute: typeof ApiPublicCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCreateRoute: ApiPublicCreateRoute,
  ApiPublicCreateUserRoute: ApiPublicCreateUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
